replicaCount: 1

image:
  repository: minterteam/tx-debug-web
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

podSecurityContext: {}

securityContext: {}

service:
  port: 80

ingress:
  domain: ""
  tlsname: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
